// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Wed Oct 24 22:46:03 2018

control_path control_path_inst
(
	.opcode(opcode_sig) ,	// input [0:15] opcode_sig
	.current_state(current_state_sig) ,	// input [0:4] current_state_sig
	.C(C_sig) ,	// input  C_sig
	.Z(Z_sig) ,	// input  Z_sig
	.alu_z(alu_z_sig) ,	// input  alu_z_sig
	.F0(F0_sig) ,	// input  F0_sig
	.F1(F1_sig) ,	// input  F1_sig
	.control_word(control_word_sig) ,	// output [0:27] control_word_sig
	.next_state(next_state_sig) 	// output [0:4] next_state_sig
);

